IraqWebsite/Controllers/UserMangmentController.cs
using IraqWebsite.Enums;
using IraqWebsite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IraqWebsite.AuthManager.Models;
using IraqWebsite.Services.UserService;
using IraqWebsite.AuthManager.ViewModels;
using static IraqWebsite.AuthManager.Statics.Permissions;
using Microsoft.AspNetCore.Mvc.Rendering;
using IraqWebsite.Helper;
using AutoMapper;

namespace IraqWebsite.Controllers
{
    [ServiceFilter(typeof(ActivitiesLog))]
    [Authorize]
    public class UserMangmentController : Controller
    {
        #region Feilds
        private readonly IUserService _IuserService;
        private readonly IMapper _mapper;
        private readonly RoleManager<IdentityRole> _roleManager;
        #endregion

        #region Constrector
        public UserMangmentController(IUserService userService,IMapper mapper, RoleManager<IdentityRole> roleManager)
        {
            _IuserService = userService;
            _mapper = mapper;
            _roleManager = roleManager;
        }
        #endregion

        #region Crud

        [Authorize(Policy = UserPolicy.View)]
        [HttpGet]
        public async Task<ActionResult> index()
        {
            var users = await _IuserService.GetUsers();
            foreach (var user in users)
            {
                var role = await _IuserService.GetRoleByUserId(user.UserId);
                ViewData["Roles"] = new SelectList(await _roleManager.Roles.ToListAsync(), "Name", "Name", role.Id);
            }
            return View(users);
        }

        [Authorize(Policy = UserPolicy.Create)]
        [HttpGet]
        public async Task<IActionResult> CreateUser()
        {
            if (User.Identity.Name != "software@Tm.Iq")
            {
                ViewData["Roles"] = new SelectList(_IuserService.GetRoles().Result.Where(x => x.Name != "SuperAdmin"), "Id", "Name");
            }
            else
            {
                ViewData["Roles"] = new SelectList(await _IuserService.GetRoles(), "Id", "Name");
            }
            return View();
        }

        [Authorize(Policy = UserPolicy.Create)]
        [HttpPost]
        public async Task<IActionResult> CreateUser(CreateUserViewModel model)
        {
            if(ModelState.IsValid)
            {
                var x = await _IuserService.CreateUser(model);
                if (!string.IsNullOrEmpty(_IuserService.Error))
                {
                    @TempData["Message"] = _IuserService.Error;
                    ViewData["Roles"] = new SelectList(_IuserService.GetRoles().Result.Where(x => x.Name != "SuperAdmin"), "Id", "Name");
                    return View(model);
                }
                return RedirectToAction("Index");
            }
            return View (model);
        }

        [HttpPost]
        public async Task<ActionResult> ConfirmAccount(string UserId)
        {
            return Ok(await _IuserService.ConfirmAccount(UserId));
        }

        [Authorize(Policy = UserPolicy.View)]
        [HttpGet]
        public async Task<ActionResult> GetRecentUsers()
        {
            return View(await _IuserService.GetRecentUsers());
        }

        [Authorize(Policy = UserPolicy.Delete)]
        [HttpGet]
        public async Task<ActionResult> DeleteUser(string userId, bool DeleteUser)
        {
            if (DeleteUser == true)
            {
                await _IuserService.DeleteUser(userId);
            }
            return RedirectToAction(nameof(index));
        }

        [Authorize(Policy = UserPolicy.Edit)]
        [HttpGet]
        public async Task<IActionResult> EditUser(string UserId)
        {
            var user = await _IuserService.GetUserById(UserId);
            RigsterViewModel rigsterVm = new RigsterViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Company = user.Company,
                Phone = user.PhoneNumber,
                IpPhone = user.IpPhone,
                Birthday = user.Birthday,
                Gender = user.Gender,
            };
            CreateUserViewModel userVm = new CreateUserViewModel
            {
                RigsterViewModel = rigsterVm,
                Active = user.IsActive,
            };
            return View(userVm);
        }

        [Authorize(Policy = UserPolicy.Edit)]
        [HttpPost]
        public async Task<IActionResult> EditUser(CreateUserViewModel model)
        {
            await _IuserService.EditUser(model);
            if (!string.IsNullOrEmpty(_IuserService.Error))
            {
                @TempData["Message"] = _IuserService.Error;
                return View(model);
            }
            return RedirectToAction(nameof(index));
        }

        [Authorize(Policy = RolePolicy.Edit)]
        [HttpPost]
        public async Task<ActionResult> UpdateUserRole(string userId,string roleName)
        {
            await _IuserService.UpdateUserRole(userId,roleName);
            return RedirectToAction(nameof(index));
        }

        //[Authorize]
        //[HttpPost]
        //public async Task<ActionResult> Filter(UserFilterViewModel viewModel)
        //{
        //    return Ok(await _IuserService.Filter(viewModel));
        //}

        //[Authorize]
        //[HttpPost]
        //public async Task<ActionResult> SaveUserImage(IFormFile file)
        //{
        //    return Ok(await _IuserService.SaveUserImage(User.Claims.ToList()[3].ToString().Replace("Email: ", ""), file));
        //}

        [Authorize(Policy = LogPolicy.View)]
        [HttpGet]
        public async Task<IActionResult> SystemLog()
        {
            return View(await _IuserService.SystemLog());
        }

        [Authorize(Policy = LogPolicy.Delete)]
        [HttpGet]
        public async Task<IActionResult> DeleteSystemLog()
        {
            await _IuserService.DeleteSystemLog();
            return RedirectToAction(nameof(SystemLog));
        }
        
        [Authorize(Policy = LogPolicy.View)]
        [HttpGet]
        public async Task<IActionResult> AuthLog()
        {
            return View(await _IuserService.AuthLog());
        }

        [Authorize(Policy = LogPolicy.Delete)]
        [HttpGet]
        public async Task<IActionResult> DeleteAuthLog()
        {
            await _IuserService.DeleteAuthLog();
            return RedirectToAction(nameof(AuthLog));
        }

        #endregion
    }
}

IraqWebsite/Views/UserMangment/AuthLog.cshtml
@model List<IraqWebsite.AuthManager.Models.UserActivityLog>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Admin/_LayoutAdmin.cshtml";
}


<div class="card">
    <div class="card-header">
        <h3>Authentication log</h3>
        @if (User.HasClaim("Permission", "Log Delete"))
        {
            <a type="button" class="btn btn-danger" asp-controller="UserMangment" asp-action="DeleteAuthLog">Delete <i class="fa fa-trash"></i></a>
        }
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped text-center">
            <thead>
                <tr>
                    <th>AreaAccessed</th>
                    <th>Browser</th>
                    <th>IPAddress</th>
                    <th>Platform</th>
                    <th>Status</th>
                    <th>Timestamp</th>
                    <th>UserName</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.AreaAccessed
                        </td>
                        <td>
                            @item.Browser
                        </td>
                        <td>
                            @item.IPAddress
                        </td>
                        <td>
                            @item.Platform
                        </td>
                        <td>
                            @item.Status
                        </td>
                        <td>
                            @item.Timestamp
                        </td>
                        <td>
                            @item.UserName
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

IraqWebsite/Views/UserMangment/CreateUser.cshtml
@model IraqWebsite.AuthManager.ViewModels.CreateUserViewModel

@{
    ViewData["Title"] = "Create User";
    Layout = "~/Views/Shared/Admin/_LayoutAdmin.cshtml";
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Create New User</h3>
    </div>
    <div class="card-body">
        <form asp-action="CreateUser" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (TempData["Message"] != null)
            {
                <h3 style="color:red">@TempData["Message"]</h3>
            }
            else
            {
                <br />

                <br />
            }
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.FirstName" class="control-label">First Name</label>
                        <input asp-for="RigsterViewModel.FirstName" type="text" class="form-control" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.LastName" class="control-label">Last Name</label>
                        <input asp-for="RigsterViewModel.LastName" type="text" class="form-control" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.Birthday" class="control-label">Birhdate</label>
                        <input asp-for="RigsterViewModel.Birthday" class="form-control" type="date">
                        <span asp-validation-for="RigsterViewModel.Birthday" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.Email" class="control-label">Email</label>
                        <input asp-for="RigsterViewModel.Email" class="form-control" type="text" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.Email" class="text-danger"></span>
                    </div>
                </div>
               <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.Company" class="control-label">Company</label>
                        <input asp-for="RigsterViewModel.Company" class="form-control" type="text" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.Company" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.Password" class="control-label">Password</label>
                        <input asp-for="RigsterViewModel.Password" class="form-control" type="password" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.ConfirmPassword" class="control-label">Confirm Password</label>
                        <input asp-for="RigsterViewModel.ConfirmPassword" class="form-control" type="password" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.Phone" class="control-label">Phone</label>
                        <input asp-for="RigsterViewModel.Phone" class="form-control" type="text" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.Phone" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.IpPhone" class="control-label">Ip Phone</label>
                        <input asp-for="RigsterViewModel.IpPhone" class="form-control" type="text" placeholder="Enter ...">
                        <span asp-validation-for="RigsterViewModel.IpPhone" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                 <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Role" class="control-label"></label>
                        <select asp-for="Role" class="form-control" asp-items="ViewBag.Roles"></select>
                        <span asp-validation-for="Role" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="RigsterViewModel.Gender" class="control-label">Gender</label>
                        <select asp-for="RigsterViewModel.Gender" class="form-control">
                            <option>Male</option>
                            <option>Female</option>
                        </select>
                        <span asp-validation-for="RigsterViewModel.Gender" class="text-danger"></span>
                    </div>
                </div>
                
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Active" class="form-label" style="font-size:17px;margin-right:20px!important">
                            <input class="form-check-input" style="margin-left:0!important;position:relative" asp-for="Active" />
                            Make As Active
                        </label>
                    </div>
                </div>
                
            </div>
            <div class="row form-group" style="justify-content: center;">
                <input type="submit" value="Create" class="btn btn-success col-sm-3 mr-2" />
                <a class="btn btn-danger col-sm-3" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

IraqWebsite/Views/UserMangment/Index.cshtml
@model List<IraqWebsite.AuthManager.ViewModels.ListUsersViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Admin/_LayoutAdmin.cshtml";
}

<div class="card">
    <div class="card-header">
        <a type="button" class="btn btn-primary" asp-action="CreateUser">Create New</a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped text-center">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    @if (User.HasClaim("Permission", "Role View"))
                    {
                        <th>User Role</th>
                    }
                    @if (User.HasClaim("Permission", "User Edit"))
                    {
                        <th>Status</th>
                    }
                    @if (User.HasClaim("Permission", "User Edit"))
                    {
                        <th>Actions</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.FirstName</td>
                        <td>@item.LastName</td>
                        <td>@item.Email</td>
                        @if (User.HasClaim("Permission", "Role View"))
                        {
                            @if (item.Roles != null)
                            {
                                <td>
                                    <select onchange="UpdateUserRole('@item.UserId',this.value)" asp-for="@item.Roles" class="form-control" asp-items="ViewBag.Roles"></select>
                                </td>
                            }
                        }
                        <td>
                            @if (User.HasClaim("Permission", "User Edit"))
                            {
                                <div>
                                    @if (item.IsActive == true)
                                    {
                                        <div class="form-switch">
                                            <input checked class="form-check-input" type="checkbox" href="javascript:void(0);" onclick="GetCheack('@item.UserId');">
                                            <label class="form-check-label" for="check_id"><i class="fas fa-unlock fa-lg" style="color: #4dbf1d;"></i></label>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="form-switch">
                                            <input class="form-check-input" type="checkbox" href="javascript:void(0);" onclick="GetCheack('@item.UserId');">
                                            <label class="form-check-label" for="check_id"><i class="fas fa-lock fa-lg" style="color: #f73302;"></i></label>
                                        </div>
                                    }
                                </div>
                            }
                        </td>
                        @if (User.HasClaim("Permission", "User Edit"))
                        {
                            <td>
                                <a class="btn btn-primary" asp-controller="UserMangment" asp-action="EditUser" asp-route-userId="@item.UserId"><i class="fas fa-edit"></i></a>
                                @*<a class="btn btn-danger" href="javascript:void(0);" onclick="GetUser('@item.UserId','@item.Email');" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="fas fa-trash"></i></a>*@
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter" onclick="GetUser('@item.UserId','@item.Email');">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Delete Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label style="color:black;" id="UserEmail"></label>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="DeleteUser">Delete</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    var x;
    function GetUser(userId,E) {
        x = userId
        document.getElementById('UserEmail').innerHTML = 'you will Delete  ' + E;
    }
    console.log(x);
    $(function() {
        $("#DeleteUser").click(function() {
            $.ajax({
                type: "GET",
                url: "/UserMangment/DeleteUser",
                data: { "UserId": x, "DeleteUser": true },
                success: function() {
                    window.location.reload();
                },
                error: function() {
                }
            });
        });
    });


    function GetCheack(U) {
        $.ajax({
            type: "POST",
            url: "/UserMangment/ConfirmAccount",
            data: { "UserId": U },
            success: function() {
                location.reload();
            },
            error: function() {
            }
        });
    }

    function UpdateUserRole(userId, roleName) {
        $.ajax({
            type: "POST",
            url: "/UserMangment/UpdateUserRole",
            data: { "userId": userId, "roleName": roleName },
            success: function() {
            },
            error: function() {
            }
        });
    }

</script>

IraqWebsite/Views/UserMangment/SystemLog.cshtml
@model List<IraqWebsite.AuthManager.Models.UserActivityLog>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Admin/_LayoutAdmin.cshtml";
}


<div class="card">
    <div class="card-header">
        <h3>System log</h3>
        @if (User.HasClaim("Permission", "Log Delete"))
        {
            <a type="button" class="btn btn-danger" asp-controller="UserMangment" asp-action="DeleteSystemLog">Delete <i class="fa fa-trash"></i></a>
        }
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped text-center">
            <thead>
                <tr>
                    <th>AreaAccessed</th>
                    <th>Browser</th>
                    <th>IPAddress</th>
                    <th>Platform</th>
                    <th>Timestamp</th>
                    <th>UserName</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.AreaAccessed
                        </td>
                        <td>
                            @item.Browser
                        </td>
                        <td>
                            @item.IPAddress
                        </td>
                        <td>
                            @item.Platform
                        </td>
                        <td>
                            @item.Timestamp
                        </td>
                        <td>
                            @item.UserName
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->